name: real_esate_finder
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  share_plus: ^7.2.0
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0
  geolocator: ^11.0.0
  http: ^1.6.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
 
  






  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.3.0
  provider: ^6.0.5
  mailer: ^6.0.0
  flutter_slidable: ^3.0.1
  

 
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

  adaptive_icon_background: "#ffffff"                # can be color OR image
  adaptive_icon_foreground: "assets/logo.png" # front image


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      - assets/Loader_img.png
      - assets/logo.png
      - assets/load_img1.png
      - assets/load_img2.png
      - assets/load_img3.png
      - assets/login_img.png
      - assets/login_img2.png
      - assets/login_img3.png
      - assets/login_img4.png
      - assets/login_back.png
      - assets/google_icon.png
      - assets/facebook.png
      - assets/tab_img.png
      - assets/tab_img2.png
      - assets/tab_img3.png
      - assets/featured_img.png
      - assets/featured_img2.png
      - assets/featured_img3.png
      - assets/person1.png
      - assets/person2.png
      - assets/person3.png
      - assets/person4.png
      - assets/person5.png
      - assets/person_javi.jpeg

      - assets/nearby1.png
      - assets/nearby2.png
      - assets/nearby3.png
      - assets/nearby4.png
      - assets/coupan.png
      - assets/bluecoupan.png

      

      - assets/cochin.jpg
      - assets/cochin1.jpg
      - assets/cochin2.jpg


      - assets/varkala.jpg
      - assets/varkala1.jpg
      - assets/varkala2.jpg


      - assets/kovai.jpg
      - assets/kovai1.jpg
      - assets/kovai2.jpg

      
      - assets/chennai.jpg
      - assets/chennai1.jpg
      - assets/chennai2.jpg
      
     
      - assets/ooty.jpg
      - assets/ooty1.jpg
      - assets/ooty2.jpg


      
      - assets/bangalore.jpg
      - assets/bangalore1.jpg
      - assets/bangalore2.jpg

      
      - assets/fav_icon.png
      - assets/Vector.png
      - assets/resultnotfound.png
      - assets/user.png
      - assets/chat.png
      - assets/star.png
      - assets/review_icon.png
      - assets/reviews_img1.png

      
      - assets/paypal.png
      - assets/upi.png
      - assets/apple pay.png
      - assets/gpay.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

